services:
  backend:
    build:
      dockerfile: Dockerfile

    environment:
      - TODOAPP_SERVER_HOST=localhost
      - TODOAPP_SERVER_PORT=8080
      - REFLEX_API_URL=http://localhost:8000
    ports:
     - 8000:8000
    depends_on:
     - redis
  frontend:
    build:
      dockerfile: web.Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
  redis:
    image: redis
